### ISSUE TITLE
Support XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [nodenv/nodenv-default-packages#11]
At the moment, if my `~/.nodenv` is a git-checkout, it becomes a bit more difficult than it really should be to include `default-packages` in my (separate) dotfiles repo.

Ideally, I'd love it if nodenv-default-packages could look in `$XDG_CONFIG_HOME/nodenv/default-packages` if `$NODENV_ROOT/default-packages` is missing.

Thanks!

**Comment by AlJohri** [comment]
symlink it?

**Comment by ELLIOTTCABLE** [comment]
Exactly what I did, of course! But it's still good practice, and something the library could benefit from, hence the feature-request.

**Comment by jrolfs** [comment]
@ELLIOTTCABLE I recently moved `nodenv` to `$XDG_DATA_HOME/nodenv` by setting `$NODENV_ROOT` in my [`.zshenv`](https://github.com/jrolfs/dot/blob/55b59860f8d7d5f835de9715d637f8ff0945ca22/home/.zshenv#L41). I think `$XDG_DATA_HOME` is the best place for **nodenv** within the XDG convention. Everything including **nodenv-default-packages** is working just fine from there.

I can see how `$XDG_CONFIG_HOME` might be desirable for the `default-packages` configuration, but part of the beauty of `nodenv` and friends is simplicity which is achieved in part with the self-contained installation at `$NODENV_ROOT`. Even though **XDG** is becoming a popular standard I suspect maintainers here would be reticent to add the conditional logic required to support configuration outside of `$NODENV_ROOT`.

**Comment by ELLIOTTCABLE** [comment]
@jrolfs oh totes. I'm fine with any/all standards support — and you're probably right that it's a data kinda thing.
