### ISSUE TITLE
Is there a way to trigger re-installation for all installed versions if you modify your list of defaults?

### ISSUE THREAD

**Issue by jbcpollak** [nodenv/nodenv-default-packages#7]

**Comment by jasonkarns** [comment]
Not at present but that would be a nice improvement. PR welcome

See https://github.com/nodenv/nodenv-aliases as an example of a plugin that exposes subcommands (under /bin) which are leveraged by the install/uninstall hooks.

**Comment by jbcpollak** [comment]
Here's a PR, hope this works for you!

https://github.com/nodenv/nodenv-default-packages/pull/8

**Comment by jasonkarns** [comment]
closed by #8

**Comment by jasonkarns** [comment]
closed by #8
